USE [RecipeBookSystemTestDB];
GO
----------------------------------------------------------

CREATE TABLE Users
(
	UserId INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
	Name NVARCHAR(100) NOT NULL,
	Email NVARCHAR(200) NOT NULL UNIQUE,
	[Password] NVARCHAR(200) NOT NULL
)
GO

 CREATE TABLE PhotoLinks
 (
	PhotoLinkId INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
	SmallPhotoLink NVARCHAR(MAX) NULL,
	BigPhotoLink NVARCHAR(MAX) NULL,
 ) 
 GO

 CREATE TABLE ProductTypes
 (
	ProductTypeId INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
	Name NVARCHAR(100) NOT NULL UNIQUE,
	PhotoLinkId INT NULL FOREIGN KEY REFERENCES PhotoLinks(PhotoLinkId)
 )
 GO

 CREATE TABLE Products
 (
	ProductId INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
	Name NVARCHAR(100) NOT NULL,
	ProductTypeId INT NOT NULL FOREIGN KEY REFERENCES ProductTypes(ProductTypeId) ON UPDATE CASCADE,
	Proteins REAL NOT NULL CHECK (Proteins >= 0 AND Proteins <= 100) DEFAULT 0,
	Fats REAL NOT NULL CHECK (Fats >= 0 AND Fats <= 100) DEFAULT 0,
	Carbohydrates REAL NOT NULL CHECK (Carbohydrates >= 0 AND Carbohydrates <= 100) DEFAULT 0,
	PhotoLinkId INT NULL FOREIGN KEY REFERENCES PhotoLinks(PhotoLinkId) ON DELETE SET NULL
 ) 
 GO

 CREATE TABLE Dishes
 (
	DishId INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
	Name NVARCHAR(100) NOT NULL,
	PhotoLinkId INT NULL FOREIGN KEY REFERENCES PhotoLinks(PhotoLinkId),
	CookingInstructions NVARCHAR(MAX) NULL
 )
 GO

 CREATE TABLE Ingredients
 (
	IngredientId INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
	DishId INT NOT NULL FOREIGN KEY REFERENCES Dishes(DishId) ON DELETE CASCADE,
	ProductId INT NULL FOREIGN KEY REFERENCES Products(ProductId) ON DELETE SET NULL,
	[Weight] REAL NULL
 )
 GO


 CREATE TABLE UsersDishes
(
	UserDisheId INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
	UserId INT NOT NULL FOREIGN KEY REFERENCES Users(UserId) ON DELETE CASCADE,
	DishId INT NOT NULL FOREIGN KEY REFERENCES Dishes(DishId) ON DELETE CASCADE
)
